title: Nicholas Vachon # your name (or website title) here
logo: "/images/KapacityKoldingZoom.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <b>Machine Learning Engineer</b>
  <br><br> 
  -  Specialised in Deep Learning and NLP
  <br>
  - 15 years of experience in management
  <br>
  - Business oriented
  <br><br>
  <a href="https://www.linkedin.com/in/vachonnicholas/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/Vachonni">View My GitHub</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
